with-expecter: true
packages:
  github.com/greenlab/ingestion/internal/application:
    config:
      dir: internal/mocks/application
      outpkg: mockapplication
    interfaces:
      Writer:
      EventPublisher:
