// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockchannel

import (
	context "context"

	channel "github.com/greenlab/device-registry/internal/domain/channel"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChannelRepository is an autogenerated mock type for the ChannelRepository type
type MockChannelRepository struct {
	mock.Mock
}

type MockChannelRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelRepository) EXPECT() *MockChannelRepository_Expecter {
	return &MockChannelRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ch
func (_m *MockChannelRepository) Create(ctx context.Context, ch *channel.Channel) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *channel.Channel) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChannelRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *channel.Channel
func (_e *MockChannelRepository_Expecter) Create(ctx interface{}, ch interface{}) *MockChannelRepository_Create_Call {
	return &MockChannelRepository_Create_Call{Call: _e.mock.On("Create", ctx, ch)}
}

func (_c *MockChannelRepository_Create_Call) Run(run func(ctx context.Context, ch *channel.Channel)) *MockChannelRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*channel.Channel))
	})
	return _c
}

func (_c *MockChannelRepository_Create_Call) Return(_a0 error) *MockChannelRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelRepository_Create_Call) RunAndReturn(run func(context.Context, *channel.Channel) error) *MockChannelRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockChannelRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChannelRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChannelRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockChannelRepository_Delete_Call {
	return &MockChannelRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockChannelRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChannelRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelRepository_Delete_Call) Return(_a0 error) *MockChannelRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockChannelRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockChannelRepository) GetByID(ctx context.Context, id uuid.UUID) (*channel.Channel, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *channel.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*channel.Channel, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *channel.Channel); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*channel.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChannelRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChannelRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockChannelRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockChannelRepository_GetByID_Call {
	return &MockChannelRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockChannelRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockChannelRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelRepository_GetByID_Call) Return(_a0 *channel.Channel, _a1 error) *MockChannelRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*channel.Channel, error)) *MockChannelRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByDevice provides a mock function with given fields: ctx, deviceID, limit, offset
func (_m *MockChannelRepository) ListByDevice(ctx context.Context, deviceID uuid.UUID, limit int, offset int) ([]*channel.Channel, int64, error) {
	ret := _m.Called(ctx, deviceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByDevice")
	}

	var r0 []*channel.Channel
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*channel.Channel, int64, error)); ok {
		return rf(ctx, deviceID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*channel.Channel); ok {
		r0 = rf(ctx, deviceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*channel.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, deviceID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, deviceID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChannelRepository_ListByDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByDevice'
type MockChannelRepository_ListByDevice_Call struct {
	*mock.Call
}

// ListByDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockChannelRepository_Expecter) ListByDevice(ctx interface{}, deviceID interface{}, limit interface{}, offset interface{}) *MockChannelRepository_ListByDevice_Call {
	return &MockChannelRepository_ListByDevice_Call{Call: _e.mock.On("ListByDevice", ctx, deviceID, limit, offset)}
}

func (_c *MockChannelRepository_ListByDevice_Call) Run(run func(ctx context.Context, deviceID uuid.UUID, limit int, offset int)) *MockChannelRepository_ListByDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockChannelRepository_ListByDevice_Call) Return(_a0 []*channel.Channel, _a1 int64, _a2 error) *MockChannelRepository_ListByDevice_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChannelRepository_ListByDevice_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*channel.Channel, int64, error)) *MockChannelRepository_ListByDevice_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWorkspace provides a mock function with given fields: ctx, workspaceID, limit, offset
func (_m *MockChannelRepository) ListByWorkspace(ctx context.Context, workspaceID uuid.UUID, limit int, offset int) ([]*channel.Channel, int64, error) {
	ret := _m.Called(ctx, workspaceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByWorkspace")
	}

	var r0 []*channel.Channel
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*channel.Channel, int64, error)); ok {
		return rf(ctx, workspaceID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*channel.Channel); ok {
		r0 = rf(ctx, workspaceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*channel.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, workspaceID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, workspaceID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockChannelRepository_ListByWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWorkspace'
type MockChannelRepository_ListByWorkspace_Call struct {
	*mock.Call
}

// ListByWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockChannelRepository_Expecter) ListByWorkspace(ctx interface{}, workspaceID interface{}, limit interface{}, offset interface{}) *MockChannelRepository_ListByWorkspace_Call {
	return &MockChannelRepository_ListByWorkspace_Call{Call: _e.mock.On("ListByWorkspace", ctx, workspaceID, limit, offset)}
}

func (_c *MockChannelRepository_ListByWorkspace_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, limit int, offset int)) *MockChannelRepository_ListByWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockChannelRepository_ListByWorkspace_Call) Return(_a0 []*channel.Channel, _a1 int64, _a2 error) *MockChannelRepository_ListByWorkspace_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockChannelRepository_ListByWorkspace_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*channel.Channel, int64, error)) *MockChannelRepository_ListByWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ch
func (_m *MockChannelRepository) Update(ctx context.Context, ch *channel.Channel) error {
	ret := _m.Called(ctx, ch)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *channel.Channel) error); ok {
		r0 = rf(ctx, ch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChannelRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - ch *channel.Channel
func (_e *MockChannelRepository_Expecter) Update(ctx interface{}, ch interface{}) *MockChannelRepository_Update_Call {
	return &MockChannelRepository_Update_Call{Call: _e.mock.On("Update", ctx, ch)}
}

func (_c *MockChannelRepository_Update_Call) Run(run func(ctx context.Context, ch *channel.Channel)) *MockChannelRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*channel.Channel))
	})
	return _c
}

func (_c *MockChannelRepository_Update_Call) Return(_a0 error) *MockChannelRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelRepository_Update_Call) RunAndReturn(run func(context.Context, *channel.Channel) error) *MockChannelRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannelRepository creates a new instance of MockChannelRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelRepository {
	mock := &MockChannelRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
