// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockfield

import (
	context "context"

	field "github.com/greenlab/device-registry/internal/domain/field"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockFieldRepository is an autogenerated mock type for the FieldRepository type
type MockFieldRepository struct {
	mock.Mock
}

type MockFieldRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFieldRepository) EXPECT() *MockFieldRepository_Expecter {
	return &MockFieldRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, f
func (_m *MockFieldRepository) Create(ctx context.Context, f *field.Field) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *field.Field) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFieldRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockFieldRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - f *field.Field
func (_e *MockFieldRepository_Expecter) Create(ctx interface{}, f interface{}) *MockFieldRepository_Create_Call {
	return &MockFieldRepository_Create_Call{Call: _e.mock.On("Create", ctx, f)}
}

func (_c *MockFieldRepository_Create_Call) Run(run func(ctx context.Context, f *field.Field)) *MockFieldRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*field.Field))
	})
	return _c
}

func (_c *MockFieldRepository_Create_Call) Return(_a0 error) *MockFieldRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldRepository_Create_Call) RunAndReturn(run func(context.Context, *field.Field) error) *MockFieldRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockFieldRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFieldRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockFieldRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFieldRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockFieldRepository_Delete_Call {
	return &MockFieldRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockFieldRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFieldRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFieldRepository_Delete_Call) Return(_a0 error) *MockFieldRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockFieldRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockFieldRepository) GetByID(ctx context.Context, id uuid.UUID) (*field.Field, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *field.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*field.Field, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *field.Field); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*field.Field)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFieldRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockFieldRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockFieldRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockFieldRepository_GetByID_Call {
	return &MockFieldRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockFieldRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockFieldRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFieldRepository_GetByID_Call) Return(_a0 *field.Field, _a1 error) *MockFieldRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFieldRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*field.Field, error)) *MockFieldRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByChannel provides a mock function with given fields: ctx, channelID
func (_m *MockFieldRepository) ListByChannel(ctx context.Context, channelID uuid.UUID) ([]*field.Field, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListByChannel")
	}

	var r0 []*field.Field
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*field.Field, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*field.Field); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*field.Field)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockFieldRepository_ListByChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByChannel'
type MockFieldRepository_ListByChannel_Call struct {
	*mock.Call
}

// ListByChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
func (_e *MockFieldRepository_Expecter) ListByChannel(ctx interface{}, channelID interface{}) *MockFieldRepository_ListByChannel_Call {
	return &MockFieldRepository_ListByChannel_Call{Call: _e.mock.On("ListByChannel", ctx, channelID)}
}

func (_c *MockFieldRepository_ListByChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID)) *MockFieldRepository_ListByChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockFieldRepository_ListByChannel_Call) Return(_a0 []*field.Field, _a1 error) *MockFieldRepository_ListByChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockFieldRepository_ListByChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*field.Field, error)) *MockFieldRepository_ListByChannel_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, f
func (_m *MockFieldRepository) Update(ctx context.Context, f *field.Field) error {
	ret := _m.Called(ctx, f)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *field.Field) error); ok {
		r0 = rf(ctx, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockFieldRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockFieldRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - f *field.Field
func (_e *MockFieldRepository_Expecter) Update(ctx interface{}, f interface{}) *MockFieldRepository_Update_Call {
	return &MockFieldRepository_Update_Call{Call: _e.mock.On("Update", ctx, f)}
}

func (_c *MockFieldRepository_Update_Call) Run(run func(ctx context.Context, f *field.Field)) *MockFieldRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*field.Field))
	})
	return _c
}

func (_c *MockFieldRepository_Update_Call) Return(_a0 error) *MockFieldRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFieldRepository_Update_Call) RunAndReturn(run func(context.Context, *field.Field) error) *MockFieldRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFieldRepository creates a new instance of MockFieldRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFieldRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFieldRepository {
	mock := &MockFieldRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
