// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockapplication

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockRetentionManager is an autogenerated mock type for the RetentionManager type
type MockRetentionManager struct {
	mock.Mock
}

type MockRetentionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetentionManager) EXPECT() *MockRetentionManager_Expecter {
	return &MockRetentionManager_Expecter{mock: &_m.Mock}
}

// SetRetention provides a mock function with given fields: ctx, channelID, days
func (_m *MockRetentionManager) SetRetention(ctx context.Context, channelID string, days int) error {
	ret := _m.Called(ctx, channelID, days)

	if len(ret) == 0 {
		panic("no return value specified for SetRetention")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, channelID, days)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRetentionManager_SetRetention_Call is a *mock.Call that shadows Run/Return methods
type MockRetentionManager_SetRetention_Call struct {
	*mock.Call
}

func (_e *MockRetentionManager_Expecter) SetRetention(ctx interface{}, channelID interface{}, days interface{}) *MockRetentionManager_SetRetention_Call {
	return &MockRetentionManager_SetRetention_Call{Call: _e.mock.On("SetRetention", ctx, channelID, days)}
}

func (_c *MockRetentionManager_SetRetention_Call) Run(run func(ctx context.Context, channelID string, days int)) *MockRetentionManager_SetRetention_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockRetentionManager_SetRetention_Call) Return(_a0 error) *MockRetentionManager_SetRetention_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRetentionManager_SetRetention_Call) RunAndReturn(run func(context.Context, string, int) error) *MockRetentionManager_SetRetention_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRetentionManager creates a new instance of MockRetentionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetentionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetentionManager {
	mock := &MockRetentionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
