// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockauth

import (
	context "context"

	auth "github.com/greenlab/iam/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// DeleteExpired provides a mock function with given fields: ctx
func (_m *MockTokenRepository) DeleteExpired(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteExpired")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_DeleteExpired_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteExpired'
type MockTokenRepository_DeleteExpired_Call struct {
	*mock.Call
}

// DeleteExpired is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockTokenRepository_Expecter) DeleteExpired(ctx interface{}) *MockTokenRepository_DeleteExpired_Call {
	return &MockTokenRepository_DeleteExpired_Call{Call: _e.mock.On("DeleteExpired", ctx)}
}

func (_c *MockTokenRepository_DeleteExpired_Call) Run(run func(ctx context.Context)) *MockTokenRepository_DeleteExpired_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockTokenRepository_DeleteExpired_Call) Return(_a0 error) *MockTokenRepository_DeleteExpired_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_DeleteExpired_Call) RunAndReturn(run func(context.Context) error) *MockTokenRepository_DeleteExpired_Call {
	_c.Call.Return(run)
	return _c
}

// GetRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) GetRefreshToken(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetRefreshToken")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRefreshToken'
type MockTokenRepository_GetRefreshToken_Call struct {
	*mock.Call
}

// GetRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetRefreshToken(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetRefreshToken_Call {
	return &MockTokenRepository_GetRefreshToken_Call{Call: _e.mock.On("GetRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetRefreshToken_Call) Return(_a0 *auth.RefreshToken, _a1 error) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *MockTokenRepository_GetRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetAndRevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) GetAndRevokeRefreshToken(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetAndRevokeRefreshToken")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetAndRevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAndRevokeRefreshToken'
type MockTokenRepository_GetAndRevokeRefreshToken_Call struct {
	*mock.Call
}

// GetAndRevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetAndRevokeRefreshToken(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetAndRevokeRefreshToken_Call {
	return &MockTokenRepository_GetAndRevokeRefreshToken_Call{Call: _e.mock.On("GetAndRevokeRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetAndRevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetAndRevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetAndRevokeRefreshToken_Call) Return(_a0 *auth.RefreshToken, _a1 error) *MockTokenRepository_GetAndRevokeRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetAndRevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *MockTokenRepository_GetAndRevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeAllForUser provides a mock function with given fields: ctx, userID
func (_m *MockTokenRepository) RevokeAllForUser(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for RevokeAllForUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_RevokeAllForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeAllForUser'
type MockTokenRepository_RevokeAllForUser_Call struct {
	*mock.Call
}

// RevokeAllForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockTokenRepository_Expecter) RevokeAllForUser(ctx interface{}, userID interface{}) *MockTokenRepository_RevokeAllForUser_Call {
	return &MockTokenRepository_RevokeAllForUser_Call{Call: _e.mock.On("RevokeAllForUser", ctx, userID)}
}

func (_c *MockTokenRepository_RevokeAllForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockTokenRepository_RevokeAllForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenRepository_RevokeAllForUser_Call) Return(_a0 error) *MockTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_RevokeAllForUser_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTokenRepository_RevokeAllForUser_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeFamily provides a mock function with given fields: ctx, family
func (_m *MockTokenRepository) RevokeFamily(ctx context.Context, family uuid.UUID) error {
	ret := _m.Called(ctx, family)

	if len(ret) == 0 {
		panic("no return value specified for RevokeFamily")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, family)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_RevokeFamily_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeFamily'
type MockTokenRepository_RevokeFamily_Call struct {
	*mock.Call
}

// RevokeFamily is a helper method to define mock.On call
//   - ctx context.Context
//   - family uuid.UUID
func (_e *MockTokenRepository_Expecter) RevokeFamily(ctx interface{}, family interface{}) *MockTokenRepository_RevokeFamily_Call {
	return &MockTokenRepository_RevokeFamily_Call{Call: _e.mock.On("RevokeFamily", ctx, family)}
}

func (_c *MockTokenRepository_RevokeFamily_Call) Run(run func(ctx context.Context, family uuid.UUID)) *MockTokenRepository_RevokeFamily_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenRepository_RevokeFamily_Call) Return(_a0 error) *MockTokenRepository_RevokeFamily_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_RevokeFamily_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTokenRepository_RevokeFamily_Call {
	_c.Call.Return(run)
	return _c
}

// RevokeRefreshToken provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for RevokeRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_RevokeRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RevokeRefreshToken'
type MockTokenRepository_RevokeRefreshToken_Call struct {
	*mock.Call
}

// RevokeRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) RevokeRefreshToken(ctx interface{}, tokenHash interface{}) *MockTokenRepository_RevokeRefreshToken_Call {
	return &MockTokenRepository_RevokeRefreshToken_Call{Call: _e.mock.On("RevokeRefreshToken", ctx, tokenHash)}
}

func (_c *MockTokenRepository_RevokeRefreshToken_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_RevokeRefreshToken_Call) Return(_a0 error) *MockTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_RevokeRefreshToken_Call) RunAndReturn(run func(context.Context, string) error) *MockTokenRepository_RevokeRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// SaveRefreshToken provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) SaveRefreshToken(ctx context.Context, token *auth.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for SaveRefreshToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_SaveRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveRefreshToken'
type MockTokenRepository_SaveRefreshToken_Call struct {
	*mock.Call
}

// SaveRefreshToken is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.RefreshToken
func (_e *MockTokenRepository_Expecter) SaveRefreshToken(ctx interface{}, token interface{}) *MockTokenRepository_SaveRefreshToken_Call {
	return &MockTokenRepository_SaveRefreshToken_Call{Call: _e.mock.On("SaveRefreshToken", ctx, token)}
}

func (_c *MockTokenRepository_SaveRefreshToken_Call) Run(run func(ctx context.Context, token *auth.RefreshToken)) *MockTokenRepository_SaveRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RefreshToken))
	})
	return _c
}

func (_c *MockTokenRepository_SaveRefreshToken_Call) Return(_a0 error) *MockTokenRepository_SaveRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_SaveRefreshToken_Call) RunAndReturn(run func(context.Context, *auth.RefreshToken) error) *MockTokenRepository_SaveRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
