// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockauth

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCacheRepository is an autogenerated mock type for the CacheRepository type
type MockCacheRepository struct {
	mock.Mock
}

type MockCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheRepository) EXPECT() *MockCacheRepository_Expecter {
	return &MockCacheRepository_Expecter{mock: &_m.Mock}
}

// BlacklistToken provides a mock function with given fields: ctx, jti, ttlSeconds
func (_m *MockCacheRepository) BlacklistToken(ctx context.Context, jti string, ttlSeconds int) error {
	ret := _m.Called(ctx, jti, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for BlacklistToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int) error); ok {
		r0 = rf(ctx, jti, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_BlacklistToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlacklistToken'
type MockCacheRepository_BlacklistToken_Call struct {
	*mock.Call
}

// BlacklistToken is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
//   - ttlSeconds int
func (_e *MockCacheRepository_Expecter) BlacklistToken(ctx interface{}, jti interface{}, ttlSeconds interface{}) *MockCacheRepository_BlacklistToken_Call {
	return &MockCacheRepository_BlacklistToken_Call{Call: _e.mock.On("BlacklistToken", ctx, jti, ttlSeconds)}
}

func (_c *MockCacheRepository_BlacklistToken_Call) Run(run func(ctx context.Context, jti string, ttlSeconds int)) *MockCacheRepository_BlacklistToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int))
	})
	return _c
}

func (_c *MockCacheRepository_BlacklistToken_Call) Return(_a0 error) *MockCacheRepository_BlacklistToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_BlacklistToken_Call) RunAndReturn(run func(context.Context, string, int) error) *MockCacheRepository_BlacklistToken_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserSession provides a mock function with given fields: ctx, userID
func (_m *MockCacheRepository) DeleteUserSession(ctx context.Context, userID string) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_DeleteUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserSession'
type MockCacheRepository_DeleteUserSession_Call struct {
	*mock.Call
}

// DeleteUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCacheRepository_Expecter) DeleteUserSession(ctx interface{}, userID interface{}) *MockCacheRepository_DeleteUserSession_Call {
	return &MockCacheRepository_DeleteUserSession_Call{Call: _e.mock.On("DeleteUserSession", ctx, userID)}
}

func (_c *MockCacheRepository_DeleteUserSession_Call) Run(run func(ctx context.Context, userID string)) *MockCacheRepository_DeleteUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_DeleteUserSession_Call) Return(_a0 error) *MockCacheRepository_DeleteUserSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_DeleteUserSession_Call) RunAndReturn(run func(context.Context, string) error) *MockCacheRepository_DeleteUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserSession provides a mock function with given fields: ctx, userID
func (_m *MockCacheRepository) GetUserSession(ctx context.Context, userID string) ([]byte, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserSession")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheRepository_GetUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserSession'
type MockCacheRepository_GetUserSession_Call struct {
	*mock.Call
}

// GetUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockCacheRepository_Expecter) GetUserSession(ctx interface{}, userID interface{}) *MockCacheRepository_GetUserSession_Call {
	return &MockCacheRepository_GetUserSession_Call{Call: _e.mock.On("GetUserSession", ctx, userID)}
}

func (_c *MockCacheRepository_GetUserSession_Call) Run(run func(ctx context.Context, userID string)) *MockCacheRepository_GetUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_GetUserSession_Call) Return(_a0 []byte, _a1 error) *MockCacheRepository_GetUserSession_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheRepository_GetUserSession_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockCacheRepository_GetUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// IsTokenBlacklisted provides a mock function with given fields: ctx, jti
func (_m *MockCacheRepository) IsTokenBlacklisted(ctx context.Context, jti string) (bool, error) {
	ret := _m.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenBlacklisted")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, jti)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCacheRepository_IsTokenBlacklisted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenBlacklisted'
type MockCacheRepository_IsTokenBlacklisted_Call struct {
	*mock.Call
}

// IsTokenBlacklisted is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *MockCacheRepository_Expecter) IsTokenBlacklisted(ctx interface{}, jti interface{}) *MockCacheRepository_IsTokenBlacklisted_Call {
	return &MockCacheRepository_IsTokenBlacklisted_Call{Call: _e.mock.On("IsTokenBlacklisted", ctx, jti)}
}

func (_c *MockCacheRepository_IsTokenBlacklisted_Call) Run(run func(ctx context.Context, jti string)) *MockCacheRepository_IsTokenBlacklisted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCacheRepository_IsTokenBlacklisted_Call) Return(_a0 bool, _a1 error) *MockCacheRepository_IsTokenBlacklisted_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCacheRepository_IsTokenBlacklisted_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockCacheRepository_IsTokenBlacklisted_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserSession provides a mock function with given fields: ctx, userID, data, ttlSeconds
func (_m *MockCacheRepository) SetUserSession(ctx context.Context, userID string, data interface{}, ttlSeconds int) error {
	ret := _m.Called(ctx, userID, data, ttlSeconds)

	if len(ret) == 0 {
		panic("no return value specified for SetUserSession")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}, int) error); ok {
		r0 = rf(ctx, userID, data, ttlSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCacheRepository_SetUserSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserSession'
type MockCacheRepository_SetUserSession_Call struct {
	*mock.Call
}

// SetUserSession is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - data interface{}
//   - ttlSeconds int
func (_e *MockCacheRepository_Expecter) SetUserSession(ctx interface{}, userID interface{}, data interface{}, ttlSeconds interface{}) *MockCacheRepository_SetUserSession_Call {
	return &MockCacheRepository_SetUserSession_Call{Call: _e.mock.On("SetUserSession", ctx, userID, data, ttlSeconds)}
}

func (_c *MockCacheRepository_SetUserSession_Call) Run(run func(ctx context.Context, userID string, data interface{}, ttlSeconds int)) *MockCacheRepository_SetUserSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}), args[3].(int))
	})
	return _c
}

func (_c *MockCacheRepository_SetUserSession_Call) Return(_a0 error) *MockCacheRepository_SetUserSession_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCacheRepository_SetUserSession_Call) RunAndReturn(run func(context.Context, string, interface{}, int) error) *MockCacheRepository_SetUserSession_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCacheRepository creates a new instance of MockCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheRepository {
	mock := &MockCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
