// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockauth

import (
	context "context"

	auth "github.com/greenlab/iam/internal/domain/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishEmailVerified provides a mock function with given fields: ctx, userID
func (_m *MockEventPublisher) PublishEmailVerified(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PublishEmailVerified")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishEmailVerified_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishEmailVerified'
type MockEventPublisher_PublishEmailVerified_Call struct {
	*mock.Call
}

// PublishEmailVerified is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEventPublisher_Expecter) PublishEmailVerified(ctx interface{}, userID interface{}) *MockEventPublisher_PublishEmailVerified_Call {
	return &MockEventPublisher_PublishEmailVerified_Call{Call: _e.mock.On("PublishEmailVerified", ctx, userID)}
}

func (_c *MockEventPublisher_PublishEmailVerified_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEventPublisher_PublishEmailVerified_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEventPublisher_PublishEmailVerified_Call) Return(_a0 error) *MockEventPublisher_PublishEmailVerified_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishEmailVerified_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEventPublisher_PublishEmailVerified_Call {
	_c.Call.Return(run)
	return _c
}

// PublishPasswordChanged provides a mock function with given fields: ctx, userID
func (_m *MockEventPublisher) PublishPasswordChanged(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for PublishPasswordChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishPasswordChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishPasswordChanged'
type MockEventPublisher_PublishPasswordChanged_Call struct {
	*mock.Call
}

// PublishPasswordChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockEventPublisher_Expecter) PublishPasswordChanged(ctx interface{}, userID interface{}) *MockEventPublisher_PublishPasswordChanged_Call {
	return &MockEventPublisher_PublishPasswordChanged_Call{Call: _e.mock.On("PublishPasswordChanged", ctx, userID)}
}

func (_c *MockEventPublisher_PublishPasswordChanged_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockEventPublisher_PublishPasswordChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockEventPublisher_PublishPasswordChanged_Call) Return(_a0 error) *MockEventPublisher_PublishPasswordChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishPasswordChanged_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockEventPublisher_PublishPasswordChanged_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserLoggedIn provides a mock function with given fields: ctx, user, ip
func (_m *MockEventPublisher) PublishUserLoggedIn(ctx context.Context, user *auth.User, ip string) error {
	ret := _m.Called(ctx, user, ip)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserLoggedIn")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.User, string) error); ok {
		r0 = rf(ctx, user, ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishUserLoggedIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserLoggedIn'
type MockEventPublisher_PublishUserLoggedIn_Call struct {
	*mock.Call
}

// PublishUserLoggedIn is a helper method to define mock.On call
//   - ctx context.Context
//   - user *auth.User
//   - ip string
func (_e *MockEventPublisher_Expecter) PublishUserLoggedIn(ctx interface{}, user interface{}, ip interface{}) *MockEventPublisher_PublishUserLoggedIn_Call {
	return &MockEventPublisher_PublishUserLoggedIn_Call{Call: _e.mock.On("PublishUserLoggedIn", ctx, user, ip)}
}

func (_c *MockEventPublisher_PublishUserLoggedIn_Call) Run(run func(ctx context.Context, user *auth.User, ip string)) *MockEventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.User), args[2].(string))
	})
	return _c
}

func (_c *MockEventPublisher_PublishUserLoggedIn_Call) Return(_a0 error) *MockEventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishUserLoggedIn_Call) RunAndReturn(run func(context.Context, *auth.User, string) error) *MockEventPublisher_PublishUserLoggedIn_Call {
	_c.Call.Return(run)
	return _c
}

// PublishUserRegistered provides a mock function with given fields: ctx, user
func (_m *MockEventPublisher) PublishUserRegistered(ctx context.Context, user *auth.User) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for PublishUserRegistered")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.User) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishUserRegistered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishUserRegistered'
type MockEventPublisher_PublishUserRegistered_Call struct {
	*mock.Call
}

// PublishUserRegistered is a helper method to define mock.On call
//   - ctx context.Context
//   - user *auth.User
func (_e *MockEventPublisher_Expecter) PublishUserRegistered(ctx interface{}, user interface{}) *MockEventPublisher_PublishUserRegistered_Call {
	return &MockEventPublisher_PublishUserRegistered_Call{Call: _e.mock.On("PublishUserRegistered", ctx, user)}
}

func (_c *MockEventPublisher_PublishUserRegistered_Call) Run(run func(ctx context.Context, user *auth.User)) *MockEventPublisher_PublishUserRegistered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.User))
	})
	return _c
}

func (_c *MockEventPublisher_PublishUserRegistered_Call) Return(_a0 error) *MockEventPublisher_PublishUserRegistered_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishUserRegistered_Call) RunAndReturn(run func(context.Context, *auth.User) error) *MockEventPublisher_PublishUserRegistered_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
