// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocktenant

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tenant "github.com/greenlab/iam/internal/domain/tenant"

	uuid "github.com/google/uuid"
)

// MockWorkspaceRepository is an autogenerated mock type for the WorkspaceRepository type
type MockWorkspaceRepository struct {
	mock.Mock
}

type MockWorkspaceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceRepository) EXPECT() *MockWorkspaceRepository_Expecter {
	return &MockWorkspaceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, ws
func (_m *MockWorkspaceRepository) Create(ctx context.Context, ws *tenant.Workspace) error {
	ret := _m.Called(ctx, ws)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.Workspace) error); ok {
		r0 = rf(ctx, ws)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkspaceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockWorkspaceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - ws *tenant.Workspace
func (_e *MockWorkspaceRepository_Expecter) Create(ctx interface{}, ws interface{}) *MockWorkspaceRepository_Create_Call {
	return &MockWorkspaceRepository_Create_Call{Call: _e.mock.On("Create", ctx, ws)}
}

func (_c *MockWorkspaceRepository_Create_Call) Run(run func(ctx context.Context, ws *tenant.Workspace)) *MockWorkspaceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tenant.Workspace))
	})
	return _c
}

func (_c *MockWorkspaceRepository_Create_Call) Return(_a0 error) *MockWorkspaceRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkspaceRepository_Create_Call) RunAndReturn(run func(context.Context, *tenant.Workspace) error) *MockWorkspaceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockWorkspaceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockWorkspaceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockWorkspaceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockWorkspaceRepository_Delete_Call {
	return &MockWorkspaceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockWorkspaceRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWorkspaceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkspaceRepository_Delete_Call) Return(_a0 error) *MockWorkspaceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockWorkspaceRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockWorkspaceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockWorkspaceRepository) GetByID(ctx context.Context, id uuid.UUID) (*tenant.Workspace, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *tenant.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*tenant.Workspace, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *tenant.Workspace); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenant.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkspaceRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockWorkspaceRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockWorkspaceRepository_GetByID_Call {
	return &MockWorkspaceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockWorkspaceRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockWorkspaceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkspaceRepository_GetByID_Call) Return(_a0 *tenant.Workspace, _a1 error) *MockWorkspaceRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkspaceRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*tenant.Workspace, error)) *MockWorkspaceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByOrg provides a mock function with given fields: ctx, orgID
func (_m *MockWorkspaceRepository) ListByOrg(ctx context.Context, orgID uuid.UUID) ([]*tenant.Workspace, error) {
	ret := _m.Called(ctx, orgID)

	if len(ret) == 0 {
		panic("no return value specified for ListByOrg")
	}

	var r0 []*tenant.Workspace
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]*tenant.Workspace, error)); ok {
		return rf(ctx, orgID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []*tenant.Workspace); ok {
		r0 = rf(ctx, orgID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tenant.Workspace)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orgID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockWorkspaceRepository_ListByOrg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByOrg'
type MockWorkspaceRepository_ListByOrg_Call struct {
	*mock.Call
}

// ListByOrg is a helper method to define mock.On call
//   - ctx context.Context
//   - orgID uuid.UUID
func (_e *MockWorkspaceRepository_Expecter) ListByOrg(ctx interface{}, orgID interface{}) *MockWorkspaceRepository_ListByOrg_Call {
	return &MockWorkspaceRepository_ListByOrg_Call{Call: _e.mock.On("ListByOrg", ctx, orgID)}
}

func (_c *MockWorkspaceRepository_ListByOrg_Call) Run(run func(ctx context.Context, orgID uuid.UUID)) *MockWorkspaceRepository_ListByOrg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkspaceRepository_ListByOrg_Call) Return(_a0 []*tenant.Workspace, _a1 error) *MockWorkspaceRepository_ListByOrg_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockWorkspaceRepository_ListByOrg_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]*tenant.Workspace, error)) *MockWorkspaceRepository_ListByOrg_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, ws
func (_m *MockWorkspaceRepository) Update(ctx context.Context, ws *tenant.Workspace) error {
	ret := _m.Called(ctx, ws)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.Workspace) error); ok {
		r0 = rf(ctx, ws)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ListMembers provides a mock function with given fields: ctx, workspaceID
func (_m *MockWorkspaceRepository) ListMembers(ctx context.Context, workspaceID string) ([]tenant.WorkspaceMember, error) {
	ret := _m.Called(ctx, workspaceID)
	var r0 []tenant.WorkspaceMember
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]tenant.WorkspaceMember, error)); ok {
		return rf(ctx, workspaceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []tenant.WorkspaceMember); ok {
		r0 = rf(ctx, workspaceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tenant.WorkspaceMember)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, workspaceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// AddMember provides a mock function with given fields: ctx, m
func (_m *MockWorkspaceRepository) AddMember(ctx context.Context, m tenant.WorkspaceMember) error {
	ret := _m.Called(ctx, m)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, tenant.WorkspaceMember) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UpdateMember provides a mock function with given fields: ctx, workspaceID, userID, role
func (_m *MockWorkspaceRepository) UpdateMember(ctx context.Context, workspaceID, userID, role string) error {
	ret := _m.Called(ctx, workspaceID, userID, role)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, workspaceID, userID, role)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RemoveMember provides a mock function with given fields: ctx, workspaceID, userID
func (_m *MockWorkspaceRepository) RemoveMember(ctx context.Context, workspaceID, userID string) error {
	ret := _m.Called(ctx, workspaceID, userID)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, workspaceID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NewMockWorkspaceRepository creates a new instance of MockWorkspaceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceRepository {
	mock := &MockWorkspaceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
