// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocktenant

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tenant "github.com/greenlab/iam/internal/domain/tenant"

	uuid "github.com/google/uuid"
)

// MockOrgRepository is an autogenerated mock type for the OrgRepository type
type MockOrgRepository struct {
	mock.Mock
}

type MockOrgRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrgRepository) EXPECT() *MockOrgRepository_Expecter {
	return &MockOrgRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, org
func (_m *MockOrgRepository) Create(ctx context.Context, org *tenant.Org) error {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.Org) error); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrgRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOrgRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - org *tenant.Org
func (_e *MockOrgRepository_Expecter) Create(ctx interface{}, org interface{}) *MockOrgRepository_Create_Call {
	return &MockOrgRepository_Create_Call{Call: _e.mock.On("Create", ctx, org)}
}

func (_c *MockOrgRepository_Create_Call) Run(run func(ctx context.Context, org *tenant.Org)) *MockOrgRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tenant.Org))
	})
	return _c
}

func (_c *MockOrgRepository_Create_Call) Return(_a0 error) *MockOrgRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrgRepository_Create_Call) RunAndReturn(run func(context.Context, *tenant.Org) error) *MockOrgRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockOrgRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrgRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockOrgRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrgRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockOrgRepository_Delete_Call {
	return &MockOrgRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockOrgRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrgRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrgRepository_Delete_Call) Return(_a0 error) *MockOrgRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrgRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockOrgRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockOrgRepository) GetByID(ctx context.Context, id uuid.UUID) (*tenant.Org, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *tenant.Org
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*tenant.Org, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *tenant.Org); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenant.Org)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockOrgRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockOrgRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockOrgRepository_GetByID_Call {
	return &MockOrgRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockOrgRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockOrgRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockOrgRepository_GetByID_Call) Return(_a0 *tenant.Org, _a1 error) *MockOrgRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*tenant.Org, error)) *MockOrgRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *MockOrgRepository) GetBySlug(ctx context.Context, slug string) (*tenant.Org, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 *tenant.Org
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tenant.Org, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tenant.Org); ok {
		r0 = rf(ctx, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenant.Org)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrgRepository_GetBySlug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBySlug'
type MockOrgRepository_GetBySlug_Call struct {
	*mock.Call
}

// GetBySlug is a helper method to define mock.On call
//   - ctx context.Context
//   - slug string
func (_e *MockOrgRepository_Expecter) GetBySlug(ctx interface{}, slug interface{}) *MockOrgRepository_GetBySlug_Call {
	return &MockOrgRepository_GetBySlug_Call{Call: _e.mock.On("GetBySlug", ctx, slug)}
}

func (_c *MockOrgRepository_GetBySlug_Call) Run(run func(ctx context.Context, slug string)) *MockOrgRepository_GetBySlug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOrgRepository_GetBySlug_Call) Return(_a0 *tenant.Org, _a1 error) *MockOrgRepository_GetBySlug_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrgRepository_GetBySlug_Call) RunAndReturn(run func(context.Context, string) (*tenant.Org, error)) *MockOrgRepository_GetBySlug_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, limit, offset
func (_m *MockOrgRepository) List(ctx context.Context, limit int, offset int) ([]*tenant.Org, int64, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*tenant.Org
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*tenant.Org, int64, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*tenant.Org); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tenant.Org)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) int64); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, int) error); ok {
		r2 = rf(ctx, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockOrgRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockOrgRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *MockOrgRepository_Expecter) List(ctx interface{}, limit interface{}, offset interface{}) *MockOrgRepository_List_Call {
	return &MockOrgRepository_List_Call{Call: _e.mock.On("List", ctx, limit, offset)}
}

func (_c *MockOrgRepository_List_Call) Run(run func(ctx context.Context, limit int, offset int)) *MockOrgRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *MockOrgRepository_List_Call) Return(_a0 []*tenant.Org, _a1 int64, _a2 error) *MockOrgRepository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockOrgRepository_List_Call) RunAndReturn(run func(context.Context, int, int) ([]*tenant.Org, int64, error)) *MockOrgRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, org
func (_m *MockOrgRepository) Update(ctx context.Context, org *tenant.Org) error {
	ret := _m.Called(ctx, org)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.Org) error); ok {
		r0 = rf(ctx, org)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOrgRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrgRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - org *tenant.Org
func (_e *MockOrgRepository_Expecter) Update(ctx interface{}, org interface{}) *MockOrgRepository_Update_Call {
	return &MockOrgRepository_Update_Call{Call: _e.mock.On("Update", ctx, org)}
}

func (_c *MockOrgRepository_Update_Call) Run(run func(ctx context.Context, org *tenant.Org)) *MockOrgRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tenant.Org))
	})
	return _c
}

func (_c *MockOrgRepository_Update_Call) Return(_a0 error) *MockOrgRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOrgRepository_Update_Call) RunAndReturn(run func(context.Context, *tenant.Org) error) *MockOrgRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrgRepository creates a new instance of MockOrgRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrgRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrgRepository {
	mock := &MockOrgRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
