// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocktenant

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	tenant "github.com/greenlab/iam/internal/domain/tenant"
)

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// ListAPIKeys provides a mock function with given fields: ctx, tenantID
func (_m *MockAPIKeyRepository) ListAPIKeys(ctx context.Context, tenantID string) ([]tenant.APIKey, error) {
	ret := _m.Called(ctx, tenantID)
	var r0 []tenant.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]tenant.APIKey, error)); ok {
		return rf(ctx, tenantID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []tenant.APIKey); ok {
		r0 = rf(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]tenant.APIKey)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// CreateAPIKey provides a mock function with given fields: ctx, key
func (_m *MockAPIKeyRepository) CreateAPIKey(ctx context.Context, key tenant.APIKey) error {
	ret := _m.Called(ctx, key)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, tenant.APIKey) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// DeleteAPIKey provides a mock function with given fields: ctx, id, tenantID
func (_m *MockAPIKeyRepository) DeleteAPIKey(ctx context.Context, id, tenantID string) error {
	ret := _m.Called(ctx, id, tenantID)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, id, tenantID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
