// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocktenant

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	uuid "github.com/google/uuid"
	tenant "github.com/greenlab/iam/internal/domain/tenant"
)

// MockWorkspaceAPIKeyRepository is an autogenerated mock type for the WorkspaceAPIKeyRepository type
type MockWorkspaceAPIKeyRepository struct {
	mock.Mock
}

type MockWorkspaceAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWorkspaceAPIKeyRepository) EXPECT() *MockWorkspaceAPIKeyRepository_Expecter {
	return &MockWorkspaceAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Save provides a mock function with given fields: ctx, key
func (_m *MockWorkspaceAPIKeyRepository) Save(ctx context.Context, key *tenant.WorkspaceAPIKey) error {
	ret := _m.Called(ctx, key)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *tenant.WorkspaceAPIKey) error); ok {
		r0 = rf(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAPIKeyRepository_Save_Call is a *mock.Call that shadows *call with type safe method.
type MockWorkspaceAPIKeyRepository_Save_Call struct {
	*mock.Call
}

func (_e *MockWorkspaceAPIKeyRepository_Expecter) Save(ctx interface{}, key interface{}) *MockWorkspaceAPIKeyRepository_Save_Call {
	return &MockWorkspaceAPIKeyRepository_Save_Call{Call: _e.mock.On("Save", ctx, key)}
}

func (_c *MockWorkspaceAPIKeyRepository_Save_Call) Run(run func(ctx context.Context, key *tenant.WorkspaceAPIKey)) *MockWorkspaceAPIKeyRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*tenant.WorkspaceAPIKey))
	})
	return _c
}

func (_c *MockWorkspaceAPIKeyRepository_Save_Call) Return(_a0 error) *MockWorkspaceAPIKeyRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

// GetByPrefix provides a mock function with given fields: ctx, keyPrefix
func (_m *MockWorkspaceAPIKeyRepository) GetByPrefix(ctx context.Context, keyPrefix string) (*tenant.WorkspaceAPIKey, error) {
	ret := _m.Called(ctx, keyPrefix)
	var r0 *tenant.WorkspaceAPIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*tenant.WorkspaceAPIKey, error)); ok {
		return rf(ctx, keyPrefix)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *tenant.WorkspaceAPIKey); ok {
		r0 = rf(ctx, keyPrefix)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*tenant.WorkspaceAPIKey)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, keyPrefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWorkspaceAPIKeyRepository_GetByPrefix_Call is a *mock.Call that shadows *call with type safe method.
type MockWorkspaceAPIKeyRepository_GetByPrefix_Call struct {
	*mock.Call
}

func (_e *MockWorkspaceAPIKeyRepository_Expecter) GetByPrefix(ctx interface{}, keyPrefix interface{}) *MockWorkspaceAPIKeyRepository_GetByPrefix_Call {
	return &MockWorkspaceAPIKeyRepository_GetByPrefix_Call{Call: _e.mock.On("GetByPrefix", ctx, keyPrefix)}
}

func (_c *MockWorkspaceAPIKeyRepository_GetByPrefix_Call) Run(run func(ctx context.Context, keyPrefix string)) *MockWorkspaceAPIKeyRepository_GetByPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockWorkspaceAPIKeyRepository_GetByPrefix_Call) Return(_a0 *tenant.WorkspaceAPIKey, _a1 error) *MockWorkspaceAPIKeyRepository_GetByPrefix_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// ListByWorkspace provides a mock function with given fields: ctx, workspaceID, limit, offset
func (_m *MockWorkspaceAPIKeyRepository) ListByWorkspace(ctx context.Context, workspaceID uuid.UUID, limit int, offset int) ([]*tenant.WorkspaceAPIKey, int64, error) {
	ret := _m.Called(ctx, workspaceID, limit, offset)
	var r0 []*tenant.WorkspaceAPIKey
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*tenant.WorkspaceAPIKey, int64, error)); ok {
		return rf(ctx, workspaceID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*tenant.WorkspaceAPIKey); ok {
		r0 = rf(ctx, workspaceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*tenant.WorkspaceAPIKey)
		}
	}
	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, workspaceID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, workspaceID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWorkspaceAPIKeyRepository_ListByWorkspace_Call is a *mock.Call that shadows *call with type safe method.
type MockWorkspaceAPIKeyRepository_ListByWorkspace_Call struct {
	*mock.Call
}

func (_e *MockWorkspaceAPIKeyRepository_Expecter) ListByWorkspace(ctx interface{}, workspaceID interface{}, limit interface{}, offset interface{}) *MockWorkspaceAPIKeyRepository_ListByWorkspace_Call {
	return &MockWorkspaceAPIKeyRepository_ListByWorkspace_Call{Call: _e.mock.On("ListByWorkspace", ctx, workspaceID, limit, offset)}
}

func (_c *MockWorkspaceAPIKeyRepository_ListByWorkspace_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, limit int, offset int)) *MockWorkspaceAPIKeyRepository_ListByWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockWorkspaceAPIKeyRepository_ListByWorkspace_Call) Return(_a0 []*tenant.WorkspaceAPIKey, _a1 int64, _a2 error) *MockWorkspaceAPIKeyRepository_ListByWorkspace_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id, workspaceID
func (_m *MockWorkspaceAPIKeyRepository) Revoke(ctx context.Context, id uuid.UUID, workspaceID uuid.UUID) error {
	ret := _m.Called(ctx, id, workspaceID)
	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, id, workspaceID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWorkspaceAPIKeyRepository_Revoke_Call is a *mock.Call that shadows *call with type safe method.
type MockWorkspaceAPIKeyRepository_Revoke_Call struct {
	*mock.Call
}

func (_e *MockWorkspaceAPIKeyRepository_Expecter) Revoke(ctx interface{}, id interface{}, workspaceID interface{}) *MockWorkspaceAPIKeyRepository_Revoke_Call {
	return &MockWorkspaceAPIKeyRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id, workspaceID)}
}

func (_c *MockWorkspaceAPIKeyRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID, workspaceID uuid.UUID)) *MockWorkspaceAPIKeyRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockWorkspaceAPIKeyRepository_Revoke_Call) Return(_a0 error) *MockWorkspaceAPIKeyRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

// NewMockWorkspaceAPIKeyRepository creates a new instance of MockWorkspaceAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWorkspaceAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWorkspaceAPIKeyRepository {
	mock := &MockWorkspaceAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
