// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdevice

import (
	context "context"

	device "github.com/greenlab/device-registry/internal/domain/device"
	mock "github.com/stretchr/testify/mock"
)

// MockDeviceCacheRepository is an autogenerated mock type for the DeviceCacheRepository type
type MockDeviceCacheRepository struct {
	mock.Mock
}

type MockDeviceCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceCacheRepository) EXPECT() *MockDeviceCacheRepository_Expecter {
	return &MockDeviceCacheRepository_Expecter{mock: &_m.Mock}
}

// DeleteDevice provides a mock function with given fields: ctx, deviceID, apiKey
func (_m *MockDeviceCacheRepository) DeleteDevice(ctx context.Context, deviceID string, apiKey string) error {
	ret := _m.Called(ctx, deviceID, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, deviceID, apiKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceCacheRepository_DeleteDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDevice'
type MockDeviceCacheRepository_DeleteDevice_Call struct {
	*mock.Call
}

// DeleteDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - deviceID string
//   - apiKey string
func (_e *MockDeviceCacheRepository_Expecter) DeleteDevice(ctx interface{}, deviceID interface{}, apiKey interface{}) *MockDeviceCacheRepository_DeleteDevice_Call {
	return &MockDeviceCacheRepository_DeleteDevice_Call{Call: _e.mock.On("DeleteDevice", ctx, deviceID, apiKey)}
}

func (_c *MockDeviceCacheRepository_DeleteDevice_Call) Run(run func(ctx context.Context, deviceID string, apiKey string)) *MockDeviceCacheRepository_DeleteDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockDeviceCacheRepository_DeleteDevice_Call) Return(_a0 error) *MockDeviceCacheRepository_DeleteDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceCacheRepository_DeleteDevice_Call) RunAndReturn(run func(context.Context, string, string) error) *MockDeviceCacheRepository_DeleteDevice_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeviceByAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *MockDeviceCacheRepository) GetDeviceByAPIKey(ctx context.Context, apiKey string) (*device.Device, error) {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for GetDeviceByAPIKey")
	}

	var r0 *device.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*device.Device, error)); ok {
		return rf(ctx, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *device.Device); ok {
		r0 = rf(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*device.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceCacheRepository_GetDeviceByAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeviceByAPIKey'
type MockDeviceCacheRepository_GetDeviceByAPIKey_Call struct {
	*mock.Call
}

// GetDeviceByAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockDeviceCacheRepository_Expecter) GetDeviceByAPIKey(ctx interface{}, apiKey interface{}) *MockDeviceCacheRepository_GetDeviceByAPIKey_Call {
	return &MockDeviceCacheRepository_GetDeviceByAPIKey_Call{Call: _e.mock.On("GetDeviceByAPIKey", ctx, apiKey)}
}

func (_c *MockDeviceCacheRepository_GetDeviceByAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockDeviceCacheRepository_GetDeviceByAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceCacheRepository_GetDeviceByAPIKey_Call) Return(_a0 *device.Device, _a1 error) *MockDeviceCacheRepository_GetDeviceByAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceCacheRepository_GetDeviceByAPIKey_Call) RunAndReturn(run func(context.Context, string) (*device.Device, error)) *MockDeviceCacheRepository_GetDeviceByAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetDevice provides a mock function with given fields: ctx, _a1
func (_m *MockDeviceCacheRepository) SetDevice(ctx context.Context, _a1 *device.Device) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for SetDevice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *device.Device) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceCacheRepository_SetDevice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDevice'
type MockDeviceCacheRepository_SetDevice_Call struct {
	*mock.Call
}

// SetDevice is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *device.Device
func (_e *MockDeviceCacheRepository_Expecter) SetDevice(ctx interface{}, _a1 interface{}) *MockDeviceCacheRepository_SetDevice_Call {
	return &MockDeviceCacheRepository_SetDevice_Call{Call: _e.mock.On("SetDevice", ctx, _a1)}
}

func (_c *MockDeviceCacheRepository_SetDevice_Call) Run(run func(ctx context.Context, _a1 *device.Device)) *MockDeviceCacheRepository_SetDevice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*device.Device))
	})
	return _c
}

func (_c *MockDeviceCacheRepository_SetDevice_Call) Return(_a0 error) *MockDeviceCacheRepository_SetDevice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceCacheRepository_SetDevice_Call) RunAndReturn(run func(context.Context, *device.Device) error) *MockDeviceCacheRepository_SetDevice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceCacheRepository creates a new instance of MockDeviceCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceCacheRepository {
	mock := &MockDeviceCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
