// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockdevice

import (
	context "context"

	device "github.com/greenlab/device-registry/internal/domain/device"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockDeviceRepository is an autogenerated mock type for the DeviceRepository type
type MockDeviceRepository struct {
	mock.Mock
}

type MockDeviceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDeviceRepository) EXPECT() *MockDeviceRepository_Expecter {
	return &MockDeviceRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, d
func (_m *MockDeviceRepository) Create(ctx context.Context, d *device.Device) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *device.Device) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockDeviceRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - d *device.Device
func (_e *MockDeviceRepository_Expecter) Create(ctx interface{}, d interface{}) *MockDeviceRepository_Create_Call {
	return &MockDeviceRepository_Create_Call{Call: _e.mock.On("Create", ctx, d)}
}

func (_c *MockDeviceRepository_Create_Call) Run(run func(ctx context.Context, d *device.Device)) *MockDeviceRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*device.Device))
	})
	return _c
}

func (_c *MockDeviceRepository_Create_Call) Return(_a0 error) *MockDeviceRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceRepository_Create_Call) RunAndReturn(run func(context.Context, *device.Device) error) *MockDeviceRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockDeviceRepository) Delete(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDeviceRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockDeviceRepository_Delete_Call {
	return &MockDeviceRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDeviceRepository_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceRepository_Delete_Call) Return(_a0 error) *MockDeviceRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceRepository_Delete_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockDeviceRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByAPIKey provides a mock function with given fields: ctx, apiKey
func (_m *MockDeviceRepository) GetByAPIKey(ctx context.Context, apiKey string) (*device.Device, error) {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for GetByAPIKey")
	}

	var r0 *device.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*device.Device, error)); ok {
		return rf(ctx, apiKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *device.Device); ok {
		r0 = rf(ctx, apiKey)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*device.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, apiKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_GetByAPIKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByAPIKey'
type MockDeviceRepository_GetByAPIKey_Call struct {
	*mock.Call
}

// GetByAPIKey is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey string
func (_e *MockDeviceRepository_Expecter) GetByAPIKey(ctx interface{}, apiKey interface{}) *MockDeviceRepository_GetByAPIKey_Call {
	return &MockDeviceRepository_GetByAPIKey_Call{Call: _e.mock.On("GetByAPIKey", ctx, apiKey)}
}

func (_c *MockDeviceRepository_GetByAPIKey_Call) Run(run func(ctx context.Context, apiKey string)) *MockDeviceRepository_GetByAPIKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDeviceRepository_GetByAPIKey_Call) Return(_a0 *device.Device, _a1 error) *MockDeviceRepository_GetByAPIKey_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_GetByAPIKey_Call) RunAndReturn(run func(context.Context, string) (*device.Device, error)) *MockDeviceRepository_GetByAPIKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockDeviceRepository) GetByID(ctx context.Context, id uuid.UUID) (*device.Device, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *device.Device
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*device.Device, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *device.Device); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*device.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDeviceRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockDeviceRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockDeviceRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockDeviceRepository_GetByID_Call {
	return &MockDeviceRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockDeviceRepository_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockDeviceRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockDeviceRepository_GetByID_Call) Return(_a0 *device.Device, _a1 error) *MockDeviceRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDeviceRepository_GetByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*device.Device, error)) *MockDeviceRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByWorkspace provides a mock function with given fields: ctx, workspaceID, limit, offset
func (_m *MockDeviceRepository) ListByWorkspace(ctx context.Context, workspaceID uuid.UUID, limit int, offset int) ([]*device.Device, int64, error) {
	ret := _m.Called(ctx, workspaceID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListByWorkspace")
	}

	var r0 []*device.Device
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]*device.Device, int64, error)); ok {
		return rf(ctx, workspaceID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []*device.Device); ok {
		r0 = rf(ctx, workspaceID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*device.Device)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) int64); ok {
		r1 = rf(ctx, workspaceID, limit, offset)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, int) error); ok {
		r2 = rf(ctx, workspaceID, limit, offset)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockDeviceRepository_ListByWorkspace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByWorkspace'
type MockDeviceRepository_ListByWorkspace_Call struct {
	*mock.Call
}

// ListByWorkspace is a helper method to define mock.On call
//   - ctx context.Context
//   - workspaceID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockDeviceRepository_Expecter) ListByWorkspace(ctx interface{}, workspaceID interface{}, limit interface{}, offset interface{}) *MockDeviceRepository_ListByWorkspace_Call {
	return &MockDeviceRepository_ListByWorkspace_Call{Call: _e.mock.On("ListByWorkspace", ctx, workspaceID, limit, offset)}
}

func (_c *MockDeviceRepository_ListByWorkspace_Call) Run(run func(ctx context.Context, workspaceID uuid.UUID, limit int, offset int)) *MockDeviceRepository_ListByWorkspace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockDeviceRepository_ListByWorkspace_Call) Return(_a0 []*device.Device, _a1 int64, _a2 error) *MockDeviceRepository_ListByWorkspace_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockDeviceRepository_ListByWorkspace_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]*device.Device, int64, error)) *MockDeviceRepository_ListByWorkspace_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, d
func (_m *MockDeviceRepository) Update(ctx context.Context, d *device.Device) error {
	ret := _m.Called(ctx, d)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *device.Device) error); ok {
		r0 = rf(ctx, d)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDeviceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockDeviceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - d *device.Device
func (_e *MockDeviceRepository_Expecter) Update(ctx interface{}, d interface{}) *MockDeviceRepository_Update_Call {
	return &MockDeviceRepository_Update_Call{Call: _e.mock.On("Update", ctx, d)}
}

func (_c *MockDeviceRepository_Update_Call) Run(run func(ctx context.Context, d *device.Device)) *MockDeviceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*device.Device))
	})
	return _c
}

func (_c *MockDeviceRepository_Update_Call) Return(_a0 error) *MockDeviceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDeviceRepository_Update_Call) RunAndReturn(run func(context.Context, *device.Device) error) *MockDeviceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDeviceRepository creates a new instance of MockDeviceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDeviceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDeviceRepository {
	mock := &MockDeviceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
