// Code generated by mockery v2.53.6. DO NOT EDIT.

package mockapplication

import (
	context "context"

	domain "github.com/greenlab/ingestion/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// PublishReadings provides a mock function with given fields: ctx, readings
func (_m *MockEventPublisher) PublishReadings(ctx context.Context, readings []*domain.Reading) error {
	ret := _m.Called(ctx, readings)

	if len(ret) == 0 {
		panic("no return value specified for PublishReadings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Reading) error); ok {
		r0 = rf(ctx, readings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishReadings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishReadings'
type MockEventPublisher_PublishReadings_Call struct {
	*mock.Call
}

// PublishReadings is a helper method to define mock.On call
//   - ctx context.Context
//   - readings []*domain.Reading
func (_e *MockEventPublisher_Expecter) PublishReadings(ctx interface{}, readings interface{}) *MockEventPublisher_PublishReadings_Call {
	return &MockEventPublisher_PublishReadings_Call{Call: _e.mock.On("PublishReadings", ctx, readings)}
}

func (_c *MockEventPublisher_PublishReadings_Call) Run(run func(ctx context.Context, readings []*domain.Reading)) *MockEventPublisher_PublishReadings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Reading))
	})
	return _c
}

func (_c *MockEventPublisher_PublishReadings_Call) Return(_a0 error) *MockEventPublisher_PublishReadings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishReadings_Call) RunAndReturn(run func(context.Context, []*domain.Reading) error) *MockEventPublisher_PublishReadings_Call {
	_c.Call.Return(run)
	return _c
}

// PublishReplayReadings provides a mock function with given fields: ctx, readings
func (_m *MockEventPublisher) PublishReplayReadings(ctx context.Context, readings []*domain.Reading) error {
	ret := _m.Called(ctx, readings)

	if len(ret) == 0 {
		panic("no return value specified for PublishReplayReadings")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*domain.Reading) error); ok {
		r0 = rf(ctx, readings)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_PublishReplayReadings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishReplayReadings'
type MockEventPublisher_PublishReplayReadings_Call struct {
	*mock.Call
}

// PublishReplayReadings is a helper method to define mock.On call
//   - ctx context.Context
//   - readings []*domain.Reading
func (_e *MockEventPublisher_Expecter) PublishReplayReadings(ctx interface{}, readings interface{}) *MockEventPublisher_PublishReplayReadings_Call {
	return &MockEventPublisher_PublishReplayReadings_Call{Call: _e.mock.On("PublishReplayReadings", ctx, readings)}
}

func (_c *MockEventPublisher_PublishReplayReadings_Call) Run(run func(ctx context.Context, readings []*domain.Reading)) *MockEventPublisher_PublishReplayReadings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]*domain.Reading))
	})
	return _c
}

func (_c *MockEventPublisher_PublishReplayReadings_Call) Return(_a0 error) *MockEventPublisher_PublishReplayReadings_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_PublishReplayReadings_Call) RunAndReturn(run func(context.Context, []*domain.Reading) error) *MockEventPublisher_PublishReplayReadings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
